const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" })[character]);

export function dashboardHtml({ admin = false } = {}) {
  const title = admin ? "ServersEye 管理后台" : "ServersEye 状态";
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#fff;color:#111;font:15px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}main{max-width:1120px;margin:auto;padding:36px 22px 64px}header{display:flex;justify-content:space-between;align-items:baseline;border-bottom:2px solid #111;padding-bottom:18px;margin-bottom:24px}h1{font-size:26px;margin:0;letter-spacing:-.04em}a{color:#111}button,input{font:inherit;border:1px solid #111;border-radius:8px;background:#fff;color:#111;padding:9px 12px}button{cursor:pointer;background:#111;color:#fff}button.danger{background:#fff;color:#111;border-color:#c00}button:hover{opacity:.78}.muted{color:#666;font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:14px}.card{border:1px solid #111;border-radius:12px;padding:17px}.card h2{font-size:17px;margin:0 0 12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tag{font-size:12px;padding:3px 7px;border:1px solid #111;border-radius:999px;float:right}.online{background:#111;color:#fff}.offline{color:#666;border-color:#aaa}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px}.metric{border-top:1px solid #ddd;padding-top:7px}.metric b{display:block;font-size:18px}.empty{border:1px dashed #777;border-radius:12px;padding:25px;color:#666}table{border-collapse:collapse;width:100%;min-width:760px}th,td{text-align:left;border-bottom:1px solid #ddd;padding:11px 8px;vertical-align:middle}th{font-size:12px;color:#666}.table-wrap{overflow:auto}.login{max-width:400px;border:1px solid #111;border-radius:12px;padding:20px}.login input{width:100%;margin:10px 0}.actions{display:flex;gap:8px;align-items:center}@media(max-width:600px){main{padding:24px 15px}.grid{grid-template-columns:1fr}header{align-items:flex-start;gap:10px;flex-direction:column}}
</style></head><body><main><header><div><h1>${title}</h1><div class="muted">${admin ? "仅限管理员使用" : "实时服务器状态"}</div></div><a href="${admin ? "/" : "/admin"}">${admin ? "公开状态页" : "管理入口"}</a></header><section id="app"></section></main>
<script>
const isAdmin=${admin}; const app=document.querySelector('#app');
const escapeHtml=${escapeHtml.toString()};
const number=(value,suffix='')=>value===null||value===undefined?'—':escapeHtml(value)+suffix;
const bytes=value=>{if(value===null||value===undefined)return '—';const units=['B','KB','MB','GB','TB'];let i=0,n=Number(value);while(n>=1024&&i<units.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+units[i]};
const date=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'尚未上报';
function publicCard(agent){const m=agent.metrics||{},disk=m.disk||{};return '<article class="card"><span class="tag '+(agent.online?'online':'offline')+'">'+(agent.online?'在线':'离线')+'</span><h2>'+escapeHtml(agent.name)+'</h2><div class="muted">最后上报：'+date(agent.last_seen_at)+'</div><div class="metrics"><div class="metric">CPU<b>'+number(m.cpu_percent,'%')+'</b></div><div class="metric">内存<b>'+number(m.memory_percent,'%')+'</b></div><div class="metric">磁盘<b>'+number(disk.used&&disk.total?Math.round(disk.used/disk.total*100):null,'%')+'</b></div><div class="metric">运行时长<b>'+number(m.uptime_seconds?Math.floor(m.uptime_seconds/3600):null,' h')+'</b></div></div></article>'}
async function renderPublic(){try{const response=await fetch('/api/status');if(!response.ok)throw Error();const data=await response.json();app.innerHTML=data.agents.length?'<div class="grid">'+data.agents.map(publicCard).join('')+'</div>':'<div class="empty">暂时没有可展示的服务器。</div>'}catch{app.innerHTML='<div class="empty">无法取得服务器状态，请稍后刷新。</div>'}}
function adminLogin(message=''){app.innerHTML='<form class="login" id="login"><b>管理员验证</b><div class="muted">令牌只保存在当前浏览器标签页。</div><input type="password" id="token" autocomplete="current-password" placeholder="ADMIN_TOKEN"><button>进入后台</button><div class="muted">'+escapeHtml(message)+'</div></form>';document.querySelector('#login').onsubmit=event=>{event.preventDefault();sessionStorage.setItem('serverseye-admin-token',document.querySelector('#token').value);renderAdmin()}}
function adminTable(agents){return '<div class="table-wrap"><table><thead><tr><th>名称</th><th>状态</th><th>CPU</th><th>内存</th><th>最后上报</th><th></th></tr></thead><tbody>'+agents.map(agent=>{const m=agent.metrics||{};const online=agent.updated_at&&Date.now()-agent.updated_at<90000;return '<tr><td>'+escapeHtml(agent.name)+'</td><td>'+ (online?'在线':'离线') +'</td><td>'+number(m.cpu_percent,'%')+'</td><td>'+number(m.memory_percent,'%')+'</td><td>'+date(agent.updated_at)+'</td><td><button class="danger" data-id="'+escapeHtml(agent.id)+'">删除</button></td></tr>'}).join('')+'</tbody></table></div>'}
async function renderAdmin(){const token=sessionStorage.getItem('serverseye-admin-token');if(!token)return adminLogin();try{const response=await fetch('/api/agents',{headers:{Authorization:'Bearer '+token}});if(response.status===401){sessionStorage.removeItem('serverseye-admin-token');return adminLogin('令牌无效。')}if(!response.ok)throw Error();const data=await response.json();app.innerHTML='<div class="actions" style="margin-bottom:16px"><button id="refresh">刷新</button><button id="logout" class="danger">退出</button><span class="muted">共 '+data.agents.length+' 台服务器</span></div>'+(data.agents.length?adminTable(data.agents):'<div class="empty">还没有被控服务器。</div>');document.querySelector('#refresh').onclick=renderAdmin;document.querySelector('#logout').onclick=()=>{sessionStorage.removeItem('serverseye-admin-token');adminLogin()};document.querySelectorAll('[data-id]').forEach(button=>button.onclick=async()=>{if(!confirm('确定删除这台服务器吗？被控端之后无法继续上报。'))return;const result=await fetch('/api/agents/'+button.dataset.id,{method:'DELETE',headers:{Authorization:'Bearer '+token}});if(!result.ok)return alert('删除失败');renderAdmin()})}catch{app.innerHTML='<div class="empty">无法加载管理数据。</div>'}}
isAdmin?renderAdmin():renderPublic();if(!isAdmin)setInterval(renderPublic,20000);
</script></body></html>`;
}
