const json = (data, status = 200) => new Response(JSON.stringify(data), {
  status,
  headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" },
});

function bearer(request) {
  const value = request.headers.get("authorization") || "";
  return value.startsWith("Bearer ") ? value.slice(7) : "";
}

function authorized(request, secret) {
  return Boolean(secret) && bearer(request) === secret;
}

function agentKey(id) { return `agent:${id}`; }

async function sha256(value) {
  const bytes = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)].map((x) => x.toString(16).padStart(2, "0")).join("");
}

function randomId() {
  return crypto.randomUUID().replaceAll("-", "");
}

function clientSource(controllerUrl) {
  // This is intentionally a Python stdlib-only client so it can be fetched directly from the Worker.
  return `#!/usr/bin/env python3
\"\"\"ServerEye agent. Generated by ${controllerUrl}; no third-party Python packages required.\"\"\"
import argparse, hashlib, json, os, platform, shutil, socket, sys, time, urllib.error, urllib.request

DEFAULT_CONTROLLER = ${JSON.stringify(controllerUrl)}
CONFIG_PATH = os.environ.get("SERVEREYE_CONFIG", "/etc/servereye/agent.json")

def load_config():
    try:
        with open(CONFIG_PATH, "r", encoding="utf-8") as f: return json.load(f)
    except FileNotFoundError:
        return {}

def save_config(data):
    os.makedirs(os.path.dirname(CONFIG_PATH), mode=0o700, exist_ok=True)
    temporary = CONFIG_PATH + ".tmp"
    with open(temporary, "w", encoding="utf-8") as f: json.dump(data, f, indent=2)
    os.chmod(temporary, 0o600)
    os.replace(temporary, CONFIG_PATH)

def read_first(path):
    try:
        with open(path, encoding="utf-8") as f: return f.readline().strip()
    except OSError: return ""

def cpu_percent():
    def sample():
        values = [int(x) for x in read_first("/proc/stat").split()[1:]]
        total = sum(values); idle = values[3] + (values[4] if len(values) > 4 else 0)
        return total, idle
    try:
        total1, idle1 = sample(); time.sleep(0.15); total2, idle2 = sample()
        return round(100 * (1 - (idle2-idle1) / max(total2-total1, 1)), 1)
    except (ValueError, IndexError): return None

def mem_percent():
    fields = {}
    try:
        with open("/proc/meminfo", encoding="utf-8") as f:
            for line in f:
                key, value = line.split(":", 1); fields[key] = int(value.split()[0])
        total = fields["MemTotal"]; available = fields.get("MemAvailable", fields.get("MemFree", 0))
        return round(100 * (total - available) / total, 1)
    except (OSError, ValueError, KeyError): return None

def net_bytes():
    received = sent = 0
    try:
        with open("/proc/net/dev", encoding="utf-8") as f:
            for line in f.readlines()[2:]:
                name, values = line.split(":", 1)
                if name.strip() == "lo": continue
                counters = values.split(); received += int(counters[0]); sent += int(counters[8])
    except (OSError, ValueError, IndexError): pass
    return {"rx": received, "tx": sent}

def metrics():
    disk = shutil.disk_usage("/")
    return {
        "hostname": socket.gethostname(), "platform": platform.platform(), "python": platform.python_version(),
        "uptime_seconds": float(read_first("/proc/uptime").split()[0]) if read_first("/proc/uptime") else None,
        "load_average": list(os.getloadavg()) if hasattr(os, "getloadavg") else [],
        "cpu_percent": cpu_percent(), "memory_percent": mem_percent(),
        "disk": {"total": disk.total, "used": disk.used, "free": disk.free}, "network": net_bytes(),
        "timestamp": int(time.time())
    }

def request(url, method="GET", body=None, token=None):
    headers = {"User-Agent": "ServerEye-Agent/0.1"}
    if token: headers["Authorization"] = "Bearer " + token
    if body is not None: headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=json.dumps(body).encode() if body is not None else None, headers=headers, method=method)
    with urllib.request.urlopen(req, timeout=20) as response: return json.loads(response.read().decode())

def register(enroll_token, name):
    config = load_config(); controller = config.get("controller", DEFAULT_CONTROLLER).rstrip("/")
    data = request(controller + "/api/agents/register", "POST", {"name": name or socket.gethostname()}, enroll_token)
    config.update({"controller": controller, "agent_id": data["id"], "agent_token": data["token"]})
    save_config(config); print("Registered as " + data["id"])

def run(interval):
    config = load_config()
    required = ("controller", "agent_id", "agent_token")
    if not all(config.get(key) for key in required): raise SystemExit("Not registered. Run: servereye-agent.py register --token YOUR_ENROLL_TOKEN")
    url = config["controller"].rstrip("/") + "/api/agents/" + config["agent_id"] + "/heartbeat"
    while True:
        try: request(url, "POST", metrics(), config["agent_token"])
        except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError, ValueError) as err: print("heartbeat failed: " + str(err), file=sys.stderr)
        time.sleep(interval)

parser = argparse.ArgumentParser(description="ServerEye agent")
sub = parser.add_subparsers(dest="command", required=True)
reg = sub.add_parser("register"); reg.add_argument("--token", required=True); reg.add_argument("--name")
run_parser = sub.add_parser("run"); run_parser.add_argument("--interval", type=int, default=30)
args = parser.parse_args()
if args.command == "register": register(args.token, args.name)
else: run(max(args.interval, 5))
`;
}

function installScript(controllerUrl) {
  return `#!/usr/bin/env sh
set -eu
: "\${SERVEREYE_ENROLL_TOKEN:?Set SERVEREYE_ENROLL_TOKEN before installing}"
install_dir="\${SERVEREYE_INSTALL_DIR:-/opt/servereye}"
sudo mkdir -p "$install_dir" /etc/servereye
curl -fsSL ${JSON.stringify(controllerUrl + "/agent.py")} | sudo tee "$install_dir/servereye-agent.py" >/dev/null
sudo chmod 755 "$install_dir/servereye-agent.py"
sudo "$install_dir/servereye-agent.py" register --token "$SERVEREYE_ENROLL_TOKEN"
if command -v systemctl >/dev/null 2>&1; then
  sudo tee /etc/systemd/system/servereye.service >/dev/null <<EOF
[Unit]
Description=ServerEye monitoring agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$install_dir/servereye-agent.py run
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable --now servereye.service
  echo "Installed and started as systemd service: servereye.service"
else
  echo "Installed. Start monitoring with: sudo $install_dir/servereye-agent.py run"
fi
`;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const controllerUrl = url.origin;
    if (request.method === "GET" && url.pathname === "/") return json({ name: "ServerEye", status: "ok", install: "/install.sh" });
    if (request.method === "GET" && url.pathname === "/agent.py") return new Response(clientSource(controllerUrl), { headers: { "content-type": "text/x-python; charset=utf-8", "cache-control": "no-store" } });
    if (request.method === "GET" && url.pathname === "/install.sh") return new Response(installScript(controllerUrl), { headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" } });

    if (request.method === "POST" && url.pathname === "/api/agents/register") {
      if (!authorized(request, env.ENROLL_TOKEN)) return json({ error: "invalid enrollment token" }, 401);
      const body = await request.json().catch(() => ({}));
      const id = randomId(); const token = randomId() + randomId();
      const record = { id, name: String(body.name || "unnamed").slice(0, 128), token_hash: await sha256(token), created_at: Date.now(), updated_at: null, metrics: null };
      await env.SERVER_EYE.put(agentKey(id), JSON.stringify(record));
      return json({ id, token }, 201);
    }

    const heartbeat = url.pathname.match(/^\/api\/agents\/([a-f0-9]{32})\/heartbeat$/);
    if (request.method === "POST" && heartbeat) {
      const key = agentKey(heartbeat[1]); const raw = await env.SERVER_EYE.get(key);
      if (!raw) return json({ error: "agent not found" }, 404);
      const record = JSON.parse(raw);
      if (await sha256(bearer(request)) !== record.token_hash) return json({ error: "invalid agent token" }, 401);
      const metrics = await request.json().catch(() => null);
      if (!metrics || typeof metrics !== "object") return json({ error: "invalid metrics" }, 400);
      record.metrics = metrics; record.updated_at = Date.now();
      await env.SERVER_EYE.put(key, JSON.stringify(record));
      return json({ ok: true });
    }

    if (request.method === "GET" && url.pathname === "/api/agents") {
      if (!authorized(request, env.ADMIN_TOKEN)) return json({ error: "invalid admin token" }, 401);
      const listed = await env.SERVER_EYE.list({ prefix: "agent:" });
      const agents = await Promise.all(listed.keys.map(async ({ name }) => {
        const record = JSON.parse(await env.SERVER_EYE.get(name)); delete record.token_hash; return record;
      }));
      return json({ agents });
    }
    return json({ error: "not found" }, 404);
  },
};
