const json = (data, status = 200) => new Response(JSON.stringify(data), {
  status,
  headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" },
});

function bearer(request) {
  const value = request.headers.get("authorization") || "";
  return value.startsWith("Bearer ") ? value.slice(7) : "";
}

function authorized(request, secret) {
  return Boolean(secret) && bearer(request) === secret;
}

function agentKey(id) { return `agent:${id}`; }

async function sha256(value) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value));
  return [...new Uint8Array(digest)].map((x) => x.toString(16).padStart(2, "0")).join("");
}

function randomId() { return crypto.randomUUID().replaceAll("-", ""); }

function clientSource(controllerUrl) {
  // POSIX sh is supplied by standard Linux systems; no Python or third-party runtime is required.
  return `#!/bin/sh
# ServersEye agent, generated by ${controllerUrl}.
set -eu

DEFAULT_CONTROLLER=${JSON.stringify(controllerUrl)}
CONFIG_PATH="\${SERVERSEYE_CONFIG:-/etc/serverseye/agent.conf}"

json_escape() { printf '%s' "$1" | sed 's/[\\"]/\\\\&/g'; }

save_config() {
  umask 077
  mkdir -p "$(dirname "$CONFIG_PATH")"
  temporary="$CONFIG_PATH.tmp"
  {
    printf 'controller=%s\\n' "$CONTROLLER"
    printf 'agent_id=%s\\n' "$AGENT_ID"
    printf 'agent_token=%s\\n' "$AGENT_TOKEN"
  } > "$temporary"
  mv "$temporary" "$CONFIG_PATH"
}

load_config() {
  [ -r "$CONFIG_PATH" ] || return 1
  CONTROLLER=""; AGENT_ID=""; AGENT_TOKEN=""
  while IFS= read -r line; do
    key="$(printf '%s' "$line" | cut -d= -f1)"
    value="$(printf '%s' "$line" | cut -d= -f2-)"
    case "$key" in
      controller) CONTROLLER="$value" ;;
      agent_id) AGENT_ID="$value" ;;
      agent_token) AGENT_TOKEN="$value" ;;
    esac
  done < "$CONFIG_PATH"
  [ -n "$CONTROLLER" ] && [ -n "$AGENT_ID" ] && [ -n "$AGENT_TOKEN" ]
}

cpu_sample() {
  awk '/^cpu / { total=0; for (i=2; i<=NF; i++) total+=$i; print total, $5+$6; exit }' /proc/stat
}

cpu_percent() {
  set -- $(cpu_sample); total_before="$1"; idle_before="$2"
  sleep 1
  set -- $(cpu_sample); total_after="$1"; idle_after="$2"
  total_delta=$((total_after - total_before)); idle_delta=$((idle_after - idle_before))
  [ "$total_delta" -gt 0 ] && printf '%s' "$((100 * (total_delta - idle_delta) / total_delta))" || printf '0'
}

metrics() {
  hostname="$(hostname 2>/dev/null || printf unknown)"
  platform="$(uname -srm 2>/dev/null || printf unknown)"
  uptime="$(awk '{print $1}' /proc/uptime 2>/dev/null || printf 0)"
  load="$(awk '{print $1 "," $2 "," $3}' /proc/loadavg 2>/dev/null || printf '0,0,0')"
  memory="$(awk '/MemTotal:/ {t=$2} /MemAvailable:/ {a=$2} END {if (t) print int((t-a)*100/t); else print 0}' /proc/meminfo 2>/dev/null)"
  set -- $(df -Pk / | awk 'NR==2 {print $2*1024, $3*1024, $4*1024}')
  disk_total="\${1:-0}"; disk_used="\${2:-0}"; disk_free="\${3:-0}"
  set -- $(awk -F: 'NR>2 {n=$1; gsub(/^[[:space:]]+|[[:space:]]+$/, "", n); if (n != "lo") {gsub(/^[[:space:]]+/, "", $2); split($2, a, /[[:space:]]+/); rx+=a[1]; tx+=a[9]}} END {print rx+0, tx+0}' /proc/net/dev 2>/dev/null)
  rx="\${1:-0}"; tx="\${2:-0}"
  printf '{"hostname":"%s","platform":"%s","uptime_seconds":%s,"load_average":[%s],"cpu_percent":%s,"memory_percent":%s,"disk":{"total":%s,"used":%s,"free":%s},"network":{"rx":%s,"tx":%s},"timestamp":%s}' \
    "$(json_escape "$hostname")" "$(json_escape "$platform")" "$uptime" "$load" "$(cpu_percent)" "$memory" "$disk_total" "$disk_used" "$disk_free" "$rx" "$tx" "$(date +%s)"
}

register() {
  enroll_token="$1"; name="\${2:-$(hostname)}"; CONTROLLER="$DEFAULT_CONTROLLER"
  payload=$(printf '{"name":"%s"}' "$(json_escape "$name")")
  response=$(curl --fail --silent --show-error --location --max-time 20 -X POST "$CONTROLLER/api/agents/register" -H "Authorization: Bearer $enroll_token" -H 'Content-Type: application/json' --data "$payload") || exit 1
  AGENT_ID=$(printf '%s' "$response" | sed -n 's/.*"id":"\\([^"]*\\)".*/\\1/p')
  AGENT_TOKEN=$(printf '%s' "$response" | sed -n 's/.*"token":"\\([^"]*\\)".*/\\1/p')
  [ -n "$AGENT_ID" ] && [ -n "$AGENT_TOKEN" ] || { echo '注册响应无效' >&2; exit 1; }
  save_config
  echo "已注册 ServersEye 被控端：$AGENT_ID"
}

run() {
  interval="\${1:-30}"
  load_config || { echo '尚未注册，请先运行 register' >&2; exit 1; }
  case "$interval" in *[!0-9]*|'') echo '间隔必须是整数秒' >&2; exit 2;; esac
  [ "$interval" -ge 5 ] || interval=5
  endpoint="$CONTROLLER/api/agents/$AGENT_ID/heartbeat"
  while :; do
    payload="$(metrics)"
    curl --fail --silent --show-error --location --max-time 20 -X POST "$endpoint" -H "Authorization: Bearer $AGENT_TOKEN" -H 'Content-Type: application/json' --data "$payload" >/dev/null || echo '心跳上报失败' >&2
    sleep "$interval"
  done
}

command="\${1:-}"; [ "$#" -gt 0 ] && shift
case "$command" in
  register)
    token=""; name=""
    while [ "$#" -gt 0 ]; do
      case "$1" in
        --token) token="\${2:?--token 需要令牌}"; shift 2 ;;
        --name) name="\${2:?--name 需要名称}"; shift 2 ;;
        *) echo "未知参数：$1" >&2; exit 2 ;;
      esac
    done
    [ -n "$token" ] || { echo 'register 需要 --token' >&2; exit 2; }
    register "$token" "$name"
    ;;
  run)
    interval=30
    [ "\${1:-}" = "--interval" ] && interval="\${2:?--interval 需要秒数}"
    run "$interval"
    ;;
  *) echo '用法：serverseye-agent.sh register --token TOKEN [--name NAME] | run [--interval 秒]' >&2; exit 2 ;;
esac
`;
}

function installScript(controllerUrl) {
  return `#!/bin/sh
set -eu
: "\${SERVERSEYE_ENROLL_TOKEN:?Set SERVERSEYE_ENROLL_TOKEN before installing}"
install_dir="\${SERVERSEYE_INSTALL_DIR:-/opt/serverseye}"
sudo mkdir -p "$install_dir" /etc/serverseye
curl -fsSL ${JSON.stringify(controllerUrl + "/agent.sh")} | sudo tee "$install_dir/serverseye-agent.sh" >/dev/null
sudo chmod 755 "$install_dir/serverseye-agent.sh"
sudo "$install_dir/serverseye-agent.sh" register --token "$SERVERSEYE_ENROLL_TOKEN"
if command -v systemctl >/dev/null 2>&1; then
  sudo tee /etc/systemd/system/serverseye.service >/dev/null <<EOF
[Unit]
Description=ServersEye monitoring agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$install_dir/serverseye-agent.sh run
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable --now serverseye.service
  echo "Installed and started as systemd service: serverseye.service"
else
  echo "Installed. Start monitoring with: sudo $install_dir/serverseye-agent.sh run"
fi
`;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const controllerUrl = url.origin;
    if (request.method === "GET" && url.pathname === "/") return json({ name: "ServersEye", status: "ok", install: "/install.sh" });
    if (request.method === "GET" && url.pathname === "/agent.sh") return new Response(clientSource(controllerUrl), { headers: { "content-type": "text/x-shellscript; charset=utf-8", "cache-control": "no-store" } });
    if (request.method === "GET" && url.pathname === "/install.sh") return new Response(installScript(controllerUrl), { headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" } });

    if (request.method === "POST" && url.pathname === "/api/agents/register") {
      if (!authorized(request, env.ENROLL_TOKEN)) return json({ error: "invalid enrollment token" }, 401);
      const body = await request.json().catch(() => ({}));
      const id = randomId(); const token = randomId() + randomId();
      const record = { id, name: String(body.name || "unnamed").slice(0, 128), token_hash: await sha256(token), created_at: Date.now(), updated_at: null, metrics: null };
      await env.SERVER_EYE.put(agentKey(id), JSON.stringify(record));
      return json({ id, token }, 201);
    }

    const heartbeat = url.pathname.match(/^\/api\/agents\/([a-f0-9]{32})\/heartbeat$/);
    if (request.method === "POST" && heartbeat) {
      const key = agentKey(heartbeat[1]); const raw = await env.SERVER_EYE.get(key);
      if (!raw) return json({ error: "agent not found" }, 404);
      const record = JSON.parse(raw);
      if (await sha256(bearer(request)) !== record.token_hash) return json({ error: "invalid agent token" }, 401);
      const metrics = await request.json().catch(() => null);
      if (!metrics || typeof metrics !== "object") return json({ error: "invalid metrics" }, 400);
      record.metrics = metrics; record.updated_at = Date.now();
      await env.SERVER_EYE.put(key, JSON.stringify(record));
      return json({ ok: true });
    }

    if (request.method === "GET" && url.pathname === "/api/agents") {
      if (!authorized(request, env.ADMIN_TOKEN)) return json({ error: "invalid admin token" }, 401);
      const listed = await env.SERVER_EYE.list({ prefix: "agent:" });
      const agents = await Promise.all(listed.keys.map(async ({ name }) => {
        const record = JSON.parse(await env.SERVER_EYE.get(name)); delete record.token_hash; return record;
      }));
      return json({ agents });
    }
    return json({ error: "not found" }, 404);
  },
};
